@extends('errors.layout')
@section('code', '403')
@section('icon', '🚫')
@section('title', 'Akses Ditolak')
@section('description', 'Anda tidak memiliki izin untuk mengakses halaman ini. Hubungi administrator jika Anda merasa ini adalah kesalahan.')
